name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

env:
  slack_params: |
    - GHL: Github
    - MSL: Microsoft
    - APL: Apple
    - GGL: Google

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: slack
        with:
          botToken: ${{ secrets.SLACK_BOT_TOKEN }}
          channelId: ${{ secrets.SLACK_CHANNEL_ID }}
          templateFile: .github/workflows/slack-blocks.json
          status: "Build Started"
          currentPhase: "Setup"
          pendingPhases: "Build, Test, Finish"
          params: ${{ env.slack_params }}
      - run: | 
          yarn
      - uses: ./
        with:
          botToken: ${{ secrets.SLACK_BOT_TOKEN }}
          channelId: ${{ secrets.SLACK_CHANNEL_ID }}
          templateFile: .github/workflows/slack-blocks.json
          status: "Build in progress"
          completedPhases: "Setup"
          currentPhase: "Build"
          pendingPhases: "Test, Finish"
          messageId: ${{ steps.slack.outputs.message_id }}
          params: ${{ env.slack_params }}
      - run: |
          yarn all
      - uses: ./
        with:
          botToken: ${{ secrets.SLACK_BOT_TOKEN }}
          channelId: ${{ secrets.SLACK_CHANNEL_ID }}
          templateFile: .github/workflows/slack-blocks.json
          status: "Build in progress"
          completedPhases: "Setup, Build"
          currentPhase: "Test"
          pendingPhases: "Finish"
          messageId: ${{ steps.slack.outputs.message_id }}
          params: ${{ env.slack_params }}
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          botToken: ${{ secrets.SLACK_BOT_TOKEN }}
          channelId: ${{ secrets.SLACK_CHANNEL_ID }}
          templateFile: .github/workflows/slack-blocks.json
          status: "SUCCESS"
          completedPhases: "Setup, Build, Test, Finish"
          params: ${{ env.slack_params }}
